site_name: CLP
docs_dir: ./docs
pages:

    - Apresentação: index.md

    - Especificações:
      - Geral: spec01-hub.md
      - CLP-coord:
        - Geral: spec02-coord.md
        - Geohash: spec02a-coord-Geohash.md
        - S2: spec02b-coord-S2.md
      - CLP-via: spec03-via.md

    - Apêndices:
      - Levantamentos: locationCodes.md
      - Siglas: spec04ap01-siglas.md
      - Comparações: comparacao.md
      - Algoritmos ingênuos: spec04ap05-ingenuos.md
      - Dados complementares: spec04ap06-dadosCompl.md
      - Detalhes técnicos: spec04ap08-auxTec.md

    - Créditos: assets/README.md

extra_javascript:
    - assets/leaflet-bing-layer.min.js
